version: "3"
services:
    image-uploader:
        image: image-uploader:latest
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8000:80"
        environment:
            FILE_PATH: "/images"
            ASPNETCORE_ENVIRONMENT: "Production"
        volumes:
            - /images